- hosts: all
  tasks:
    - package:
        name: 'httpd'
        state: present
    
    - name: 'Coping File to target node'
      copy: # module used to copy files and folder to target node
        src: '/root/ansible_workspace/page.html' # files and folder to copy
        dest: '/var/www/html/' # where to copy
    
    - name: 'Starting httpd'
      service:
        name: 'httpd'
        state: started

    - name: 'Enabling port number'
      ansible.posix.firewalld: #module used to manage firewall ports
        port: 80/tcp #port number that we want to use port/protocol
        state: enabled
